kubedl-io/kubedl

main.go
gang scheduling flag can be combined.
=> refactor: combine gang-scheduling flag.

api/pytorch/v1/types.go, api/tensorflow/v1/types.go, api/xdl/v1alpha1/types.go, api/xgboost/v1alpha1/types.go, config/crd/bases/kubeflow.org_pytorchjobs.yaml, config/crd/bases/kubeflow.org_tfjobs.yaml, config/crd/bases/xdl.alibaba.com_xdljobs.yaml, config/crd/bases/xgboostjob.kubeflow.org_xgboostjobs.yaml, go.mod, go.sum
fix #26 
1. add kubebuilder scaffold comments for status subresource.
2. update crd manifests.
3. upgrade controller-runtime to v0.3.0 by the way.
=> crd: update CRD status subresource manifests files with their type definitions.

example/xdl/xdl_job_mnist.yaml
=> add xdl example

controllers/pytorch/status.go, controllers/tensorflow/status.go, controllers/xdl/status.go, controllers/xgboost/job.go, pkg/job_controller/job.go, pkg/metrics/job_metrics.go, pkg/util/k8sutil/k8sutil.go, pkg/util/status.go
1. reduce potential repeatedly metering of JobFailure and JobRestarting.
2. optimize launch delay computation.
=> metrics: optimize launch delay computation and reduce potential repeatedly metering.

.travis.yml, scripts/docker_build_daily.sh
daily docker-build script, and there has been a cron job set on travis CI pipeline.
=> CI: add daily docker build script.

controllers/pytorch/job.go, controllers/pytorch/status.go, controllers/tensorflow/job.go, controllers/tensorflow/status.go, controllers/xdl/job.go, controllers/xdl/status.go, controllers/xgboost/job.go, pkg/job_controller/api/v1/interface.go, pkg/job_controller/job.go, pkg/job_controller/pod.go, pkg/job_controller/test_job_controller.go, pkg/test_job/v1/test_job_controller.go
=> fix: job state transition may fall into Restarting but it is actually Failed.

README.md, helm/kubedl/.helmignore, helm/kubedl/Chart.yaml, helm/kubedl/templates/NOTES.txt, helm/kubedl/templates/_helpers.tpl, helm/kubedl/templates/bases/kubeflow.org_pytorchjobs.yaml, helm/kubedl/templates/bases/kubeflow.org_tfjobs.yaml, helm/kubedl/templates/bases/xdl.kubedl.io_xdljobs.yaml, helm/kubedl/templates/bases/xgboostjob.kubeflow.org_xgboostjobs.yaml, helm/kubedl/templates/deployment.yaml, helm/kubedl/templates/namespace.yaml, helm/kubedl/templates/rbac.yaml, helm/kubedl/templates/service.yaml, helm/kubedl/templates/serviceaccount.yaml, helm/kubedl/templates/tests/test-connection.yaml, helm/kubedl/values.yaml
support variable template deployment for kubedl.
fix #43
=> support helm deployment for kubedl.

api/tensorflow/v1/defaults.go, api/tensorflow/v1/defaults_test.go, api/tensorflow/v1/types.go, config/crd/bases/kubeflow.org_pytorchjobs.yaml, config/crd/bases/kubeflow.org_tfjobs.yaml, config/crd/bases/xdl.kubedl.io_xdljobs.yaml, config/crd/bases/xgboostjob.kubeflow.org_xgboostjobs.yaml, controllers/tensorflow/status.go
@SimonCqk please take a review
=> Add success_policy feature

Makefile, main.go
=> fix election id and add CI env when run `make test`.

apis/mpi/v1/default.go, controllers/elasticdl/elasticdljob_controller.go, controllers/mars/mars.go, controllers/mars/marsjob_controller.go, controllers/mpi/mpijob_controller.go, controllers/pytorch/pytorchjob_controller.go, controllers/tensorflow/tensorflow.go, controllers/tensorflow/tfjob_controller.go, controllers/xdl/xdljob_controller.go, controllers/xgboost/xgboostjob_controller.go, pkg/job_controller/api/v1/interface.go, pkg/job_controller/hostnetwork.go, pkg/job_controller/pod.go, pkg/job_controller/service.go, pkg/job_controller/test_job_controller.go, pkg/test_job/v1/test_job_controller.go
1. optimize: enable hostnetwork implementation leveraging service with ClusterIP and optimize TF_CONFIG-with-hostnetwork for TFJob.
2. fix MPIJob panic.
=> feat: use clusterIP service for hostnetwork and optimize tf-cluster in hostnetwork mode.

controllers/elasticdl/pod.go, controllers/elasticdl/service.go, controllers/mars/pod.go, controllers/mars/service.go, controllers/mpi/pod.go, controllers/mpi/service.go, controllers/pytorch/pod.go, controllers/pytorch/service.go, controllers/tensorflow/pod.go, controllers/tensorflow/service.go, controllers/xdl/pod.go, controllers/xdl/service.go, controllers/xgboost/pod.go, controllers/xgboost/service.go, pkg/job_controller/api/v1/interface.go, pkg/job_controller/job.go, pkg/job_controller/job_test.go, pkg/job_controller/pod.go, pkg/job_controller/service.go, pkg/job_controller/test_job_controller.go, pkg/tensorboard/tensorboard.go, pkg/test_job/v1/object_kind.go, pkg/test_job/v1/test_job_controller.go, pkg/test_job/v1/types.go
refactor pod and service under controller, by extracting method
=> fix(job-ctrl): refactor pod and service

controllers/elasticdl/elasticdljob_controller.go, controllers/mars/marsjob_controller.go, controllers/mpi/mpijob_controller.go, controllers/pytorch/pytorchjob_controller.go, controllers/tensorflow/tfjob_controller.go, controllers/xdl/xdljob_controller.go, controllers/xgboost/xgboostjob_controller.go, go.mod, go.sum, pkg/util/runtime.go
eliminate status stale when etcd slow-watch, related issue: #107
=> fix:  fetch latest object bypass local cache to avoid cached data in-consistency.

cmd/options/options.go, controllers/add_elasticdl.go, controllers/add_mars.go, controllers/add_mpi.go, controllers/add_pytorch.go, controllers/add_tensorflow.go, controllers/add_xdl.go, controllers/add_xgboostjob.go, controllers/controllers.go, controllers/elasticdl/elasticdljob_controller.go, controllers/mars/marsjob_controller.go, controllers/model/modelversion_controller.go, controllers/mpi/mpijob_controller.go, controllers/pytorch/pytorchjob_controller.go, controllers/tensorflow/tfjob_controller.go, controllers/tensorflow/tfjob_controller_test.go, controllers/xdl/xdljob_controller.go, controllers/xgboost/xgboostjob_controller.go, main.go, pkg/job_controller/job_controller.go, pkg/job_controller/job_test.go
#111  
moved the JobConfiguration to a different package, because of cycle dependency otherwise
=> add parameter for model image builder

apis/model/v1alpha1/modelversion_types.go, controllers/model/modelversion_controller.go, controllers/model/storage/aws_efs_provider.go, controllers/model/storage/local_storage_provider.go, controllers/model/storage/nfs_provider.go, controllers/model/storage/storage_provider.go, controllers/serving/model.go, controllers/serving/predictor.go, example/tf/Dockerfile, example/tf/keras_model_to_estimator.py, example/tf/tf_job_mnist_export.yaml, pkg/job_controller/job.go
Fix the training job to generate the model properly.
=> fix training job to generate the model version properly

console/README.md, console/backend/pkg/auth/config_auth.go, console/backend/pkg/auth/empty_auth.go, console/backend/pkg/auth/oauth.go, console/backend/pkg/handlers/job.go, console/backend/pkg/model/converter.go, console/backend/pkg/model/job.go, console/backend/pkg/model/user_info.go, console/backend/pkg/routers/api/auth.go, console/frontend/src/components/GlobalHeader/AvatarDropdown.jsx, console/frontend/src/pages/Authorized.jsx, console/frontend/src/pages/DataConfig/index.jsx, console/frontend/src/pages/GitConfig/index.jsx
=> remove uid in authentication optional config

Makefile, helm/kubedl/crds/apps.kubedl.io_crons.yaml, helm/kubedl/crds/model.kubedl.io_modelversions.yaml, helm/kubedl/crds/serving.kubedl.io_inferences.yaml, helm/kubedl/crds/training.kubedl.io_elasticdljobs.yaml, helm/kubedl/crds/training.kubedl.io_marsjobs.yaml, helm/kubedl/crds/training.kubedl.io_mpijobs.yaml, helm/kubedl/crds/training.kubedl.io_pytorchjobs.yaml, helm/kubedl/crds/training.kubedl.io_xdljobs.yaml, helm/kubedl/crds/training.kubedl.io_xgboostjobs.yaml, helm/kubedl/templates/cluster-role-binding.yaml, helm/kubedl/templates/role.yaml
Signed-off-by: jian-he <jianhe788@gmail.com>
Added a make helm-charts command that will update the helm artifacts
=> add make helm-chart command 

apis/serving/v1alpha1/inference_types.go, apis/serving/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/serving.kubedl.io_inferences.yaml, controllers/serving/framework/tfserving.go, controllers/serving/inference_controller.go, controllers/serving/predictor.go, controllers/serving/utils.go, example/serving/tfserving.yaml
1. refine `Inference` api definition by renaming `TrafficPercentage` to `TrafficWeight`.
2.  refactor inference controller implementation for deploying an inference service without model version is feasible.
3. bug fix and other optimizations.
fix bug issued by #141
=> refactor & fix: refine serving implementation and bug fix.

.github/workflows/ci.yaml, controllers/add_modelversion.go, controllers/model/modelversion_controller.go, controllers/serving/inference_controller.go, main.go
- Make model version controlller to be setup based on if CRD is available
=> Make model version controlller to be setup based on if CRD is available

.github/workflows/image-ci.yaml
Add a github ci for generating the daily kubedl image
=> add daily image ci

.github/workflows/ci.yaml, example/tf/tf_job_mnist_distributed_simple.yaml, scripts/deploy_kubedl.sh, scripts/run_tf_test_job.sh
Signed-off-by: jian-he <jianhe788@gmail.com>
Added a simple e2e to the github action ci including: 
- setup kind cluster
- deploy kubedl controller
- run a simple distributed tf test job
fixes #148
=> add e2e to the ci

Dockerfile.dashboard, console/README.md, console/backend/pkg/constants/const.go, console/dashboard.yaml
Signed-off-by: jian-he <jianhe788@gmail.com>
- dashboard dockerfile fix 
- k8s deployment yaml
- documentation
=> dashboard dockerfile and deployment yaml and docs

config/manager/all_in_one.yaml, config/rbac/role.yaml, controllers/tensorflow/tfjob_controller.go, helm/kubedl/crds/serving.kubedl.io_inferences.yaml, helm/kubedl/templates/role.yaml
Add node list permission to the role.yaml as dashboard requires node list permission
=> add node list permission to rbac

Makefile, config/manager/kustomization.yaml
Add a make release command in makefile
=> Add a make release command in makefile

.github/workflows/ci.yaml
it seems  action `RyanSiu1995/kubebuilder-action@v1.2` went broken since yesterday, so we install `kubebuilder` via shell commands.
=> CI:  fix kubebuilder installation in workflow.

pkg/job_controller/job.go
This PR optimizes the ReconcileJobs func of JobController. It could be considered the path of https://github.com/kubedl-io/kubedl/pull/178
NONE
NONE
=> optimize the ReconcileJobs func of JobController

apis/training/v1alpha1/pytorchjob_types_test.go, apis/training/v1alpha1/tfjob_types_test.go, apis/training/v1alpha1/xdljob_types_test.go, config/crd/bases/training.kubedl.io_elasticdljobs.yaml, config/crd/bases/training.kubedl.io_marsjobs.yaml, config/crd/bases/training.kubedl.io_mpijobs.yaml, config/crd/bases/training.kubedl.io_pytorchjobs.yaml, config/crd/bases/training.kubedl.io_tfjobs.yaml, config/crd/bases/training.kubedl.io_xdljobs.yaml, config/crd/bases/training.kubedl.io_xgboostjobs.yaml, pkg/job_controller/api/v1/types.go
fix: https://github.com/kubedl-io/kubedl/issues/181#issuecomment-925860037
update operations may throw errors when job conditions is empty.
=> manifests: add omitempty tag of job conditions in status

apis/training/v1alpha1/common.go, apis/training/v1alpha1/elasticdljob_types.go, apis/training/v1alpha1/marsjob_defaults.go, apis/training/v1alpha1/marsjob_types.go, apis/training/v1alpha1/mpijob_default.go, apis/training/v1alpha1/mpijob_types.go, apis/training/v1alpha1/pytorchjob_defaults.go, apis/training/v1alpha1/pytorchjob_types.go, apis/training/v1alpha1/tfjob_defaults.go, apis/training/v1alpha1/tfjob_defaults_test.go, apis/training/v1alpha1/tfjob_types.go, apis/training/v1alpha1/xdljob_defaults.go, apis/training/v1alpha1/xdljob_defaults_test.go, apis/training/v1alpha1/xdljob_types.go, apis/training/v1alpha1/xgboostjob_defaults.go, apis/training/v1alpha1/xgboostjob_types.go
- set `TerminationMessageFallbackToLogsOnError` as default termination policy to help diagnosing problems.
#187
=> feat: enable TerminationMessageFallbackToLogsOnError termination policy by default.

controllers/elasticdl/job.go, controllers/mars/job.go, controllers/mpi/job.go, controllers/pytorch/job.go, controllers/tensorflow/job.go, controllers/xdl/job.go, controllers/xgboost/job.go
Signed-off-by: SimonCqk <cqk0100@gmail.com>
1. optimize log level when job not found in informer cache, fix issue #199 
2. ~~optimize go-imports~~
=> refactor: optimize log level and go-imports.

controllers/apps/cron_event_filters.go, controllers/apps/cron_utils.go, controllers/apps/suite_test.go, controllers/elasticdl/elasticdljob_controller.go, controllers/pytorch/service.go, controllers/pytorch/status.go
Signed-off-by: kerthcet <kerthcet@gmail.com>
forget to return when error happens && some tiny typos found when reading sourcecode
None
New to Kubedl
=> forget return when error happens

Makefile, helm/kubedl/Chart.yaml, helm/kubedl/crds/cache.kubedl.io_cachebackends.yaml, helm/kubedl/crds/model.kubedl.io_models.yaml, helm/kubedl/crds/model.kubedl.io_modelversions.yaml, helm/kubedl/crds/training.kubedl.io_elasticdljobs.yaml, helm/kubedl/crds/training.kubedl.io_marsjobs.yaml, helm/kubedl/crds/training.kubedl.io_mpijobs.yaml, helm/kubedl/crds/training.kubedl.io_pytorchjobs.yaml, helm/kubedl/crds/training.kubedl.io_tfjobs.yaml, helm/kubedl/crds/training.kubedl.io_xdljobs.yaml, helm/kubedl/crds/training.kubedl.io_xgboostjobs.yaml, helm/kubedl/templates/role.yaml
Signed-off-by: jian-he <jianhe788@gmail.com>
fix the version error in helm-chart
=> fix helm-chart version error

.gitignore, config/manager/all_in_one.yaml, config/rbac/role.yaml, helm/kubedl/crds/notebook.kubedl.io_notebooks.yaml, helm/kubedl/templates/role.yaml
update the rbac rules accordinlgy in helm-chart
=> update the rbac rules 

pkg/job_controller/job_test.go, pkg/job_controller/pod.go, pkg/job_controller/pod_test.go, pkg/util/train/train_util.go, pkg/util/train/train_util_test.go
Signed-off-by: yyh <yinghao.yyh@alibaba-inc.com>
check pod failed reason for failover, e.g., OOMKilled, Evicted and Killed.
=> fix: check pod failed reason for failover

config/manager/all_in_one.yaml
Signed-off-by: Simoncqk <cqk0100@gmail.com>
=> rbac: update cachebackends resources accessibility.

controllers/mars/pod.go, controllers/mars/service.go, controllers/mpi/pod.go, controllers/pytorch/pod.go, controllers/pytorch/service.go, controllers/tensorflow/pod.go, controllers/tensorflow/service.go, controllers/tensorflow/tfjob_controller_test.go, controllers/xdl/pod.go, controllers/xdl/service.go, controllers/xgboost/pod.go, controllers/xgboost/service.go, pkg/job_controller/job.go, pkg/job_controller/job_controller.go, pkg/job_controller/pod.go, pkg/job_controller/pod_test.go, pkg/job_controller/service.go, pkg/job_controller/test_job_controller.go, pkg/tensorboard/tensorboard.go, pkg/test_util/v1/test_job_util.go
Signed-off-by: Simoncqk <cqk0100@gmail.com>
1. scale in extra pods/services when expected replicas decreases.
2. refactor to improve code reusability and robustness.
=> feat & refactor: support scale in and improve code reusability and robustness.

config/manager/all_in_one.yaml, pkg/job_controller/service_control.go
Signed-off-by: Simoncqk <cqk0100@gmail.com>
bugfix: assign namespace for service creation to avoid admission rejection.
=> fix: assign namespace when create service.

config/manager/all_in_one.yaml, config/rbac/role.yaml, controllers/controllers.go, helm/kubedl/crds/apps.kubedl.io_crons.yaml, helm/kubedl/crds/cache.kubedl.io_cachebackends.yaml, helm/kubedl/crds/model.kubedl.io_models.yaml, helm/kubedl/crds/model.kubedl.io_modelversions.yaml, helm/kubedl/crds/notebook.kubedl.io_notebooks.yaml, helm/kubedl/crds/serving.kubedl.io_inferences.yaml, helm/kubedl/crds/training.kubedl.io_elasticdljobs.yaml, helm/kubedl/crds/training.kubedl.io_marsjobs.yaml, helm/kubedl/crds/training.kubedl.io_mpijobs.yaml, helm/kubedl/crds/training.kubedl.io_pytorchjobs.yaml, helm/kubedl/crds/training.kubedl.io_tfjobs.yaml, helm/kubedl/crds/training.kubedl.io_xdljobs.yaml, helm/kubedl/crds/training.kubedl.io_xgboostjobs.yaml, helm/kubedl/templates/role.yaml, helm/kubedl/values.yaml
Signed-off-by: Simon_CQK <cqk0100@gmail.com>
1. update helm scripts, including rbac and crd update.
2. refine rbac generation.
=> deploy: regen rbac configurations and helm deploy scripts.

controllers/model/modelversion_controller.go
https://github.com/GoogleContainerTools/kaniko#flag---skip-tls-verify
=> Skip TLS certificate validation when pushing model to a registry

pkg/gang_schedule/coscheduler/scheduler.go, pkg/gang_schedule/coscheduler/scheduler_test.go
Signed-off-by: shinytang6 <1074461480@qq.com>
=> feat: add minresource to kube-coscheduler pg

console/backend/pkg/storage/objects/apiserver/apiserver.go, controllers/xgboost/job.go, pkg/job_controller/failover_test.go
=> chore: import packages only once

.github/workflows/ci.yaml, Dockerfile, README.md, config/manager/all_in_one.yaml
1. upgrade base e2e hosted image version of ubuntu
2. refine RBAC in all_in_one.yaml
=> fix(CI/CD): upgrade base ubuntu version for running e2e tests.
