kubedl-io/kubedl

- controllers/pytorch/pytorchjob_controller.go
- controllers/pytorch/status.go
- controllers/tensorflow/status.go
- controllers/xdl/status.go
- controllers/xgboost/job.go
- example/pytorch/pytorch_job_mnist_mpi.yaml
- pkg/job_controller/job.go
1. fix pytorch panic.
2. add pytorch example yaml
3. robustness improvements in updating status(in case of invalid replica-type)
> fix: pytorch panic and other robustness improvements.

- controllers/pytorch/pytorchjob_controller.go
- controllers/tensorflow/tfjob_controller.go
- controllers/xdl/xdljob_controller.go
- controllers/xgboost/xgboostjob_controller.go
- pkg/job_controller/job.go
- pkg/job_controller/job_controller.go
- pkg/job_controller/job_test.go
- pkg/util/runtime.go
1. use backoff-state-queue to record backoff status for job instances.
2. refactor to reduce useless code.
> job controller: use backoff-state-queue to record backoff status for job instances.

- api/pytorch/v1/types.go
- api/tensorflow/v1/types.go
- api/xdl/v1alpha1/types.go
- api/xgboost/v1alpha1/types.go
- config/crd/bases/kubeflow.org_pytorchjobs.yaml
- config/crd/bases/kubeflow.org_tfjobs.yaml
- config/crd/bases/xdl.kubedl.io_xdljobs.yaml
- config/crd/bases/xgboostjob.kubeflow.org_xgboostjobs.yaml
e.g:
> $ kubectl get tfjobs -n kubedl
NAME    STATE     AGE   TTL-SECONDS   ACTIVE-SECONDS
mnist     Created   16d     100                       99999
> crd: additional columns for richer information outputs in terminal.

- api/pytorch/v1/constants.go
- api/pytorch/v1/defaults.go
- api/tensorflow/v1/constants.go
- controllers/pytorch/pytorchjob_controller.go
- pkg/job_controller/pod.go
1. bugfix: string cases mismatch when compare replica types.
2. optimization: reset pytorch replicas default restart policy, set Master to OnExitCode, set Worker to OnFailure.
3. fix: generate a new expectation when create new pod conflicts, so that controller will trigger a new reconciliation and reach a expected state finally.
> fixes and optimizations in single patch

- Makefile
- config/crd/bases/elasticdl.org_elasticdljobs.yaml
- config/crd/bases/kubedl.io_marsjobs.yaml
- config/crd/bases/kubeflow.org_mpijobs.yaml
- config/crd/bases/kubeflow.org_pytorchjobs.yaml
- config/crd/bases/kubeflow.org_tfjobs.yaml
- config/crd/bases/xdl.kubedl.io_xdljobs.yaml
- config/crd/bases/xgboostjob.kubeflow.org_xgboostjobs.yaml
- config/crd/kustomization.yaml
- config/default/kustomization.yaml
- config/manager/all_in_one.yaml
- config/manager/kustomization.yaml
1. resolve errors when running Makefile, which caused by auto-generated field 'description' in CRD manifests files and rejected by apiserver, there comes a [workaround](https://github.com/kubernetes-sigs/kubebuilder/issues/1140) from `kubebuilder` community.
> kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/xdljobs.xdl.kubedl.io created
customresourcedefinition.apiextensions.k8s.io/xgboostjobs.xgboostjob.kubeflow.org created
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "pytorchjobs.kubeflow.org" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified
Error from server …
> fix: resolve errors when running Makefile and revise manifests files.

- controllers/mpi/mpi_config.go
- controllers/mpi/pod.go
- pkg/util/quota/resources.go
isGPULauncher has a problem, which is it only support nvidia gpu resources. If I want to support other gpu resources, it does not work. I think just directly use launcherRunsWorkload to decide whether launcher runs workload is ok. Actually it leaves to the users to make a decision. And the default behavior is launcher runs workload.
Looking forward to your advice!
No
> remove isGPULauncher variable, directly replace it with launcherRunsWorkload

- controllers/mpi/mpijob_controller.go
Hi kubeDL team,
I find that the resources giving to the  init container of launcher pod of mpijob is zero. It seems unreasonable. I refers to [mpi-operator](https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1/mpi_job_controller.go) to give the init container a reasonable resources.
Looking forward to your reply.
> give resources to the init container of launcher pod of mpijob

- controllers/serving/framework/tfserving.go
- controllers/serving/inference_controller.go
- controllers/serving/utils.go
- example/serving/tfserving.yaml
- pkg/job_controller/job.go
1. requeue conflicts update operations instead of throwing exceptions.
2. fix tf-serving base model path.
3. simplify serving deployment name.
fix #145
> refine: retry on update conflicts and other refinements.

- apis/training/v1alpha1/mpijob_default.go
- controllers/mpi/mpijob_controller.go
- controllers/mpi/pod.go
1. fix Launcher self-dependency in DAG-MPI mode.
2. re-correct job config creation position in control flow.
fix #164
> fix: self-dependency in DAG-MPI and re-correct job config creation position.

- pkg/job_controller/job.go
The code that I remove is redundancy. Besides, it logs an error like
`2021-09-22T11:34:19.459Z        ERROR   controller      Reconciler error        {"controller": "MPIController", "name": "mpi-demo", "namespace": "kubedl", "error": "Operation cannot be fulfilled on mpijobs.training.kubedl.io \"mpi-demo\": the object has been modified; please apply your changes to the latest version and try again"}`
No
No
> typo: remove redundancy code

- config/manager/all_in_one.yaml
- config/rbac/role.yaml
- controllers/elasticdl/elasticdljob_controller.go
- controllers/mars/marsjob_controller.go
- controllers/mpi/mpijob_controller.go
- controllers/pytorch/pytorchjob_controller.go
- controllers/tensorflow/tfjob_controller.go
- controllers/xdl/xdljob_controller.go
- controllers/xgboost/xgboostjob_controller.go
This PR adds the volcano permission to rbac, it could be consider a patch of https://github.com/kubedl-io/kubedl/pull/161
The rbac contents refer to https://github.com/kubeflow/mpi-operator/blob/c5c0c3ef99ec9de948600766988ea7134d3d2af6/deploy/v1/mpi-operator.yaml#L142-L150 and I have tested it.
NONE
I just add the volcano permission to rbac. But the batch-scheduler and coscheduler should also add the related permission.
> update rbac about volcano

- apis/training/v1alpha1/pytorchjob_types.go
- apis/training/v1alpha1/tfjob_types.go
fix the crd definition to add omityempty to the modelversion field
#188
> add omitempty to modelversion

- controllers/mpi/mpi_config.go
I found a bug in mpijob. 
https://github.com/kubedl-io/kubedl/blob/8e231e86dc82bc80c6e044d8dd9f385100277f75/controllers/mpi/mpi_config.go#L85-L87
(a)These codes write hostfile data in configmap. It writes {mpiJob.Name}-launcher slots=1
https://github.com/kubedl-io/kubedl/blob/8e231e86dc82bc80c6e044d8dd9f385100277f75/pkg/util/util.go#L74-L77
(b)These codes decide the mpijob launcher podName. The name is {mpiJob.Name}-launcher-0
(a) and (b) conflicts.
Why do I change (b) to (a)?
Although I do not know how the kubedl/kubectl-delivery:latest was built. I guess that it's source code from
https://github.com/kubeflow/mpi-operator/blob/c5c0c3ef99ec9de948600766988ea7134d3d2af6/cmd/kubectl-delivery/app/server.go#L120. From this code, I know that kubectl-delivery use the (a) form. So I change (b) to …
> Update GenGeneralName func

- controllers/elasticdl/elasticdljob_controller.go
- controllers/elasticdl/status.go
- controllers/mars/marsjob_controller.go
- controllers/mars/status.go
- controllers/mpi/job.go
- controllers/mpi/mpijob_controller.go
- controllers/pytorch/pytorchjob_controller.go
- controllers/pytorch/status.go
- controllers/tensorflow/status.go
- controllers/tensorflow/tfjob_controller.go
- controllers/xdl/status.go
- controllers/xdl/xdljob_controller.go
- controllers/xgboost/job.go
- controllers/xgboost/xgboostjob_controller.go
- pkg/job_controller/expectations.go
add DeleteExpectations func and call it when job is delete
The detail story is below:
I deploy a mpijob using myself version(it is a little different with the official version, but it doesn't matter), but I forget to creating the rbac before, so the launcher pod doesn't create, then I delete the mpijob and create the rbac, and create the same mpijob again. The result is mpijob is created but there are no any pods created. And I found the following log. Then I check the source code and open this PR.
```
2021-10-20T11:42:12.486Z        INFO    mpi-controller  reconcile cancelled, job does not need to do reconcile or has been deleted        {"job namespace": "kubedl", "job name": "mpi-demo", "need sync": false, "deleted": false}
2021-10-20T11:42:12.486Z        DEBUG   controller …
```
> add DeleteExpectations func and call it when job is delete

- pkg/job_controller/job.go
```
Dec 9, 2021 @ 23:30:13.013 I1209 15:30:13.013155 1 job_controller.go:165] Deleting GangSchedule mpi-demo
Dec 9, 2021 @ 23:30:13.004 time="2021-12-09T15:30:13Z" level=info msg="Ignoring inactive pod default/mpi-demo-worker-0 in state Succeeded, deletion time N/A"
Dec 9, 2021 @ 23:30:13.003 I1209 15:30:13.003808 1 job_controller.go:148] gang schedule created, job name: mpi-demo ,scheduler name: volcano
Dec 9, 2021 @ 23:30:12.999 I1209 15:30:12.999139 1 job.go:86] Reconciling for job mpi-demo
```
Here are logs of my kubedl, the mpi-demo job succeed a few hours before Dec 9, 2021 @ 23:30:12.999, it reconciled for some reason. Authough it has beed succeed, the location of creating gang produced these logs, so I think the location of creating gang should be adjusted.
@SimonCqk @jian-he
> adjust the location of creating gang

- pkg/util/train/train_util.go
UnexpectedAdmissionError happens when kubelet/device-plugin misfunctions. This is not job-related failure and should be 
retryable.
no
> add UnexpectedAdmissionError as retryable failed reason

- cmd/options/options.go
- controllers/pytorch/pytorchjob_controller.go
- main.go
- pkg/job_controller/pod.go
Signed-off-by: SimonCqk <cqk0100@gmail.com>
1. support specifying host port range for hostnetwork enabled jobs.
2. bugfix for pytorchjob in hostnetwork mode.
> feat: specify available host port range for hostnetwork-enabled jobs.

- config/crd/bases/training.kubedl.io_elasticdljobs.yaml
- config/crd/bases/training.kubedl.io_marsjobs.yaml
- config/crd/bases/training.kubedl.io_mpijobs.yaml
- config/crd/bases/training.kubedl.io_pytorchjobs.yaml
- config/crd/bases/training.kubedl.io_tfjobs.yaml
- config/crd/bases/training.kubedl.io_xdljobs.yaml
- config/crd/bases/training.kubedl.io_xgboostjobs.yaml
- pkg/job_controller/api/v1/types.go
- pkg/job_controller/pod.go
Signed-off-by: yyh <yinghao.yyh@alibaba-inc.com>
Enabling part of replicas to be spot, i.e., to use resources with less SLO guarantee.
Spot replicas are suitable for stateless or fault-tolerant jobs. These replicas can be scheduled with a higher chance at lower resource pricing.
> support spot replica

- pkg/gang_schedule/batch_scheduler/scheduler.go
- pkg/gang_schedule/batch_scheduler/scheduler_test.go
- pkg/gang_schedule/coscheduler/scheduler.go
- pkg/gang_schedule/coscheduler/scheduler_test.go
- pkg/gang_schedule/interface.go
- pkg/gang_schedule/registry/registry.go
- pkg/gang_schedule/volcano_scheduler/scheduler.go
- pkg/gang_schedule/volcano_scheduler/scheduler_test.go
- pkg/job_controller/api/v1/constants.go
- pkg/job_controller/job.go
- pkg/job_controller/job_controller.go
- pkg/job_controller/pod.go
- pkg/test_util/v1/test_job_util.go
1. split gang entities by job role when DAG is enabled to eliminate dead lock.
2. optimize gang interface to explicitly distinguish plugin name with scheduler name.
fix #229
> feat(gang): split gang entities by job role when DAG is enabled.

- config/rbac/role.yaml
Signed-off-by: Aero Kang <rphoho@gmail.com>
I. Describe what this PR does
修复dashboard权限不足导致页面卡死
```
E0209 13:37:36.767187       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
E0209 13:37:52.696184       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kubedl-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0209 13:42:19.072571       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: unknown (get namespaces)
E0209 13:42:33.435321       1 reflector.go:138] …
```
> fix missing permission required

- pkg/gang_schedule/volcano_scheduler/scheduler.go
- pkg/gang_schedule/volcano_scheduler/scheduler_test.go
- pkg/util/resource_utils/resources.go
1. deliver Queue name through schedulingPolicy to volcano podgroup api
2. calculate minResources in role or job unit corresponding to DAGScheduling enabled or not.
> feat: adapt volcano queue api in scheduling policy.

- controllers/pytorch/pytorchjob_controller.go
- pkg/features/features.go
- pkg/job_controller/service.go
1. adapt pytorch distributed communication style in torch-elastic.
2. support traffic no redirect in hostnetwork mode.
Signed-off-by: SimonCqk <cqk0100@gmail.com>
> feat(host): adapt pytorch distributed communication style in torch-elastic and traffic no redirect mode.

- pkg/job_controller/job.go
- pkg/metrics/job_metrics.go
feat: Implemented metrics exposure for job status with labels: name, namespace, uid, status, reason
feat: #309
> feat: Implemented metrics exposure for job status with labels: name, namespace, uid, status, reason
